### ISSUE TITLE
Rewrite Event.re

### ISSUE THREAD

**Issue by cknitt** [reasonml-community/bs-react-native#374]
The current `Event.re` in bs-react-native-next is basically just a copy of `RNEvent.re` from the old bindings and needs to be reworked.

In my opinion, we should:

- Base these event types on the flow typedefs in https://github.com/facebook/react-native/blob/master/Libraries/Types/CoreEventTypes.js.
- Use the type names from there (e.g. `layoutEvent`, not `nativeLayoutEvent`).
- Use `Js.t` types, not abstract types (see also #371 regarding that).

I have started going into this direction with the text event types in `Text.re`. These should also be checked for correctness/completeness.

**Comment by sgny** [comment]
I went through with the rewrite but ran into problems with circular types (explained further in #373) which should be resolved before a revised PR. I'd welcome feedback, perhaps something I missed, before finishing this off.

**Comment by MoOx** [comment]
Closing as Event.bs.js is now empty. Well done!

**Comment by cknitt** [comment]
I don't think it is complete! All those SyntheticEvent and ResponderSyntheticEvent from https://github.com/facebook/react-native/blob/master/Libraries/Types/CoreEventTypes.js are still missing!

**Comment by MoOx** [comment]
Ooooops. Nice catch :)

**Comment by sgny** [comment]
> I don't think it is complete! All those SyntheticEvent and ResponderSyntheticEvent fields from https://github.com/facebook/react-native/blob/master/Libraries/Types/CoreEventTypes.js are still missing!

I mentioned that in the PR, I have them as WIP.

**Comment by MoOx** [comment]
I think you fixed this right @sgny ?

**Comment by sgny** [comment]
> I think you fixed this right @sgny ?

Yes, I think we can close this issue.
